#ifndef CLIENT_STATE_HPP
# define CLIENT_STATE_HPP

enum ClientState
{
	CLIENT_STATE_INIT = 0,
	CLIENT_STATE_USER = 1 << 1,
	CLIENT_STATE_NICK = 1 << 2,
	CLIENT_STATE_OPERATOR = 1 << 3,
	CLIENT_STATE_LOGGED = (CLIENT_STATE_USER | CLIENT_STATE_NICK),
	CLIENT_STATE_NICK_FAILED = 1 << 4,
};

#endif
